In [112]:
all_txns = []
#open the file
with open("groceries.csv") as f:
    content = f.readlines()
    txns = [x.strip() for x in content]
    for each_txn in txns:
        all_txns.append(each_txn.split(","))

In [113]:
all_txns[0:5]

[['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['whole milk'],
 ['pip fruit', 'yogurt', 'cream cheese', 'meat spreads'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product']]

In [114]:
text = "citrus fruit,semi-finished bread,margarine,ready soups"
text.split(",")

['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups']

In [115]:
import pandas as pd
import numpy as np
from mlxtend.preprocessing import TransactionEncoder

In [116]:
from mlxtend.frequent_patterns import apriori,association_rules

In [117]:
one_hot_encoding = TransactionEncoder()

In [118]:
one_hot_txns = one_hot_encoding.fit(all_txns).transform(all_txns)

In [119]:
one_hot_txns.shape

(9835, 169)

In [120]:
one_hot_txns

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False,  True, False],
       [False, False, False, ...,  True, False, False],
       ...,
       [False, False, False, ..., False,  True, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [121]:
one_hot_txns  = one_hot_txns.astype("int")

In [122]:
one_hot_encoding.columns_

['Instant food products',
 'UHT-milk',
 'abrasive cleaner',
 'artif. sweetener',
 'baby cosmetics',
 'baby food',
 'bags',
 'baking powder',
 'bathroom cleaner',
 'beef',
 'berries',
 'beverages',
 'bottled beer',
 'bottled water',
 'brandy',
 'brown bread',
 'butter',
 'butter milk',
 'cake bar',
 'candles',
 'candy',
 'canned beer',
 'canned fish',
 'canned fruit',
 'canned vegetables',
 'cat food',
 'cereals',
 'chewing gum',
 'chicken',
 'chocolate',
 'chocolate marshmallow',
 'citrus fruit',
 'cleaner',
 'cling film/bags',
 'cocoa drinks',
 'coffee',
 'condensed milk',
 'cooking chocolate',
 'cookware',
 'cream',
 'cream cheese',
 'curd',
 'curd cheese',
 'decalcifier',
 'dental care',
 'dessert',
 'detergent',
 'dish cleaner',
 'dishes',
 'dog food',
 'domestic eggs',
 'female sanitary products',
 'finished products',
 'fish',
 'flour',
 'flower (seeds)',
 'flower soil/fertilizer',
 'frankfurter',
 'frozen chicken',
 'frozen dessert',
 'frozen fish',
 'frozen fruits',
 'frozen meals',
 'frozen potato products',
 'frozen vegetables',
 'fruit/vegetable juice',
 'grapes',
 'hair spray',
 'ham',
 'hamburger meat',
 'hard cheese',
 'herbs',
 'honey',
 'house keeping products',
 'hygiene articles',
 'ice cream',
 'instant coffee',
 'jam',
 'ketchup',
 'kitchen towels',
 'kitchen utensil',
 'light bulbs',
 'liqueur',
 'liquor',
 'liquor (appetizer)',
 'liver loaf',
 'long life bakery product',
 'make up remover',
 'male cosmetics',
 'margarine',
 'mayonnaise',
 'meat',
 'meat spreads',
 'misc. beverages',
 'mustard',
 'napkins',
 'newspapers',
 'nut snack',
 'nuts/prunes',
 'oil',
 'onions',
 'organic products',
 'organic sausage',
 'other vegetables',
 'packaged fruit/vegetables',
 'pasta',
 'pastry',
 'pet care',
 'photo/film',
 'pickled vegetables',
 'pip fruit',
 'popcorn',
 'pork',
 'potato products',
 'potted plants',
 'preservation products',
 'processed cheese',
 'prosecco',
 'pudding powder',
 'ready soups',
 'red/blush wine',
 'rice',
 'roll products',
 'rolls/buns',
 'root vegetables',
 'rubbing alcohol',
 'rum',
 'salad dressing',
 'salt',
 'salty snack',
 'sauces',
 'sausage',
 'seasonal products',
 'semi-finished bread',
 'shopping bags',
 'skin care',
 'sliced cheese',
 'snack products',
 'soap',
 'soda',
 'soft cheese',
 'softener',
 'sound storage medium',
 'soups',
 'sparkling wine',
 'specialty bar',
 'specialty cheese',
 'specialty chocolate',
 'specialty fat',
 'specialty vegetables',
 'spices',
 'spread cheese',
 'sugar',
 'sweet spreads',
 'syrup',
 'tea',
 'tidbits',
 'toilet cleaner',
 'tropical fruit',
 'turkey',
 'vinegar',
 'waffles',
 'whipped/sour cream',
 'whisky',
 'white bread',
 'white wine',
 'whole milk',
 'yogurt',
 'zwieback']

In [123]:
one_hot_txns_df = pd.DataFrame(one_hot_txns,columns = one_hot_encoding.columns_)

In [124]:
one_hot_txns_df.iloc[5:10,10:20]

,berries,beverages,bottled beer,bottled water,brandy,brown bread,butter,butter milk,cake bar,candles
5,0,0,0,0,0,0,1,0,0,0
6,0,0,0,0,0,0,0,0,0,0
7,0,0,1,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0

In [125]:
one_hot_txns_df.shape

(9835, 169)

In [126]:
len(one_hot_txns_df.columns)

169

In [127]:
frequent_itemsets = apriori(one_hot_txns_df, min_support=0.02 , use_colnames=True)

In [128]:
frequent_itemsets.sample(10,random_state = 10)

      support                           itemsets
61   0.024809  (bottled water, other vegetables)
45   0.037824                      (salty snack)
39   0.193493                 (other vegetables)
63   0.028978              (bottled water, soda)
111  0.024504        (whole milk, shopping bags)
96   0.020437        (pip fruit, tropical fruit)
52   0.033859                            (sugar)
104  0.034367               (yogurt, rolls/buns)
82   0.026131      (pip fruit, other vegetables)
38   0.031012                           (onions)

In [129]:
rules = association_rules(frequent_itemsets,
                         metric = "lift",
                         min_threshold=1)

In [130]:
rules.sample(5)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
21,(citrus fruit),(whole milk),0.082766,0.255516,0.030503,0.368550,1.442377,0.009355,1.179008
9,(bottled water),(whole milk),0.110524,0.255516,0.034367,0.310948,1.216940,0.006126,1.080446
30,(frankfurter),(whole milk),0.058973,0.255516,0.020539,0.348276,1.363029,0.005470,1.142330
105,(tropical fruit),(whole milk),0.104931,0.255516,0.042298,0.403101,1.577595,0.015486,1.247252
77,(rolls/buns),(root vegetables),0.183935,0.108998,0.024301,0.132117,1.212101,0.004252,1.026638

In [131]:
rules.sort_values("confidence", ascending=False)[0:10]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
122,"(yogurt, other vegetables)",(whole milk),0.043416,0.255516,0.022267,0.512881,2.007235,0.011174,1.528340
17,(butter),(whole milk),0.055414,0.255516,0.027555,0.497248,1.946053,0.013395,1.480817
25,(curd),(whole milk),0.053279,0.255516,0.026131,0.490458,1.919481,0.012517,1.461085
116,"(root vegetables, other vegetables)",(whole milk),0.047382,0.255516,0.023183,0.489270,1.914833,0.011076,1.457687
114,"(whole milk, root vegetables)",(other vegetables),0.048907,0.193493,0.023183,0.474012,2.449770,0.013719,1.533320
29,(domestic eggs),(whole milk),0.063447,0.255516,0.029995,0.472756,1.850203,0.013783,1.412030
108,(whipped/sour cream),(whole milk),0.071683,0.255516,0.032232,0.449645,1.759754,0.013916,1.352735
91,(root vegetables),(whole milk),0.108998,0.255516,0.048907,0.448694,1.756031,0.021056,1.350401
50,(root vegetables),(other vegetables),0.108998,0.193493,0.047382,0.434701,2.246605,0.026291,1.426693
33,(frozen vegetables),(whole milk),0.048094,0.255516,0.020437,0.424947,1.663094,0.008149,1.294636

In [132]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(whole milk),(beef),0.255516,0.052466,0.021251,0.083168,1.585180,0.007845,1.033487
1,(beef),(whole milk),0.052466,0.255516,0.021251,0.405039,1.585180,0.007845,1.251315
2,(bottled water),(other vegetables),0.110524,0.193493,0.024809,0.224471,1.160101,0.003424,1.039945
3,(other vegetables),(bottled water),0.193493,0.110524,0.024809,0.128219,1.160101,0.003424,1.020297
4,(bottled water),(rolls/buns),0.110524,0.183935,0.024199,0.218951,1.190373,0.003870,1.044832
...,...,...,...,...,...,...,...,...,...
121,"(whole milk, other vegetables)",(yogurt),0.074835,0.139502,0.022267,0.297554,2.132979,0.011828,1.225003
122,"(yogurt, other vegetables)",(whole milk),0.043416,0.255516,0.022267,0.512881,2.007235,0.011174,1.528340
123,(whole milk),"(yogurt, other vegetables)",0.255516,0.043416,0.022267,0.087147,2.007235,0.011174,1.047905
124,(yogurt),"(whole milk, other vegetables)",0.139502,0.074835,0.022267,0.159621,2.132979,0.011828,1.100890
125,(other vegetables),"(whole milk, yogurt)",0.193493,0.056024,0.022267,0.115081,2.054131,0.011427,1.066737